// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKV1QTcZ3FWHclTIpf3En2cg1z4dPxagA',
    appId: '1:414645682843:web:7656f4ebd270f18c5fbc3e',
    messagingSenderId: '414645682843',
    projectId: 'yoga-e6f6f',
    authDomain: 'yoga-e6f6f.firebaseapp.com',
    storageBucket: 'yoga-e6f6f.firebasestorage.app',
    measurementId: 'G-JG5GZMFNZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJkScEqd1Jr_TZl4VzhvsCY7_fuSgQCBk',
    appId: '1:414645682843:android:2417237fc4ed5bf75fbc3e',
    messagingSenderId: '414645682843',
    projectId: 'yoga-e6f6f',
    storageBucket: 'yoga-e6f6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVB2dYnIlVS2Azknf1gfbUWtrcIXoaU0o',
    appId: '1:414645682843:ios:9cc2cae914bfc50b5fbc3e',
    messagingSenderId: '414645682843',
    projectId: 'yoga-e6f6f',
    storageBucket: 'yoga-e6f6f.firebasestorage.app',
    iosBundleId: 'com.example.yoga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVB2dYnIlVS2Azknf1gfbUWtrcIXoaU0o',
    appId: '1:414645682843:ios:9cc2cae914bfc50b5fbc3e',
    messagingSenderId: '414645682843',
    projectId: 'yoga-e6f6f',
    storageBucket: 'yoga-e6f6f.firebasestorage.app',
    iosBundleId: 'com.example.yoga',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKV1QTcZ3FWHclTIpf3En2cg1z4dPxagA',
    appId: '1:414645682843:web:4849b7d837b187d05fbc3e',
    messagingSenderId: '414645682843',
    projectId: 'yoga-e6f6f',
    authDomain: 'yoga-e6f6f.firebaseapp.com',
    storageBucket: 'yoga-e6f6f.firebasestorage.app',
    measurementId: 'G-EDTWMRSG52',
  );

}